version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: tfg_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: tfg_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/02-seed.sql:/docker-entrypoint-initdb.d/02-seed.sql 
    

volumes:
  postgres_data: