spring.application.name=TFG


spring.datasource.url=jdbc:postgresql://localhost:5433/tfg_db
spring.datasource.username=admin
spring.datasource.password=admin1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Configuracion de logs
# Guarda los logs de la aplicacion en la carpeta logs, dentro de la raiz del proyecto.
logging.file.name=logs/tfg-application.log

# Nivel general de logs de la aplicacion.
logging.level.root=INFO
logging.level.com.example.demo=DEBUG

# Formato de los logs en consola y fichero.
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

# Rotacion del fichero de logs para evitar que crezca indefinidamente.
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
